### ISSUE TITLE
Despre NimbleX

### ISSUE THREAD

**Issue by crismblog** [NimbleX/nimblex#2]
Cum nu am găsit nici o modalitate de contact am zis să scriu aici.

Din câte am observat proiectul este activ. Sunt curios de ce nu mai scoateți o imagine .iso și de ce nu îi anunțați pe cei de la DistroWatch că sunteți activi?

https://distrowatch.com/table.php?distribution=nimblex

Mulțumesc

**Comment by bogdanr** [comment]
Salut Cristi,

NimbleX is maintained because I use it but I didn't really have time for doing other things that would provide a quality and interesting distro to users.

I believe the user's behavior changed significantly in the past years so in order to make something really useful I would have to change the concept quite a bit.

My contact details are in my [CV](http://bogdan.nimblex.net/cv/).
